"""empty message

Revision ID: 88590967b36d
Revises: 15ab4a0fb91d
Create Date: 2017-11-24 15:40:59.324636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88590967b36d'
down_revision = '15ab4a0fb91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
